# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d26a2c5e249309a5c6285aac8c189831b703569dffbc29d9a02cc8f6b9f2dbcc1f2667068deff28002af475f4180138613e00704712b55d7ba1c217c7198296

test:
  secret_key_base: f2766df77bd7cd588b6fb3c5b241cc712b6c87c7fa6ccc20d0d96046c6cca63ccf1b95fdd55a7f35e154dd7fb4bc072cc0569c7727219559760e6ef0c9a6c40f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
